name: Deploy to Google Artifact Registry

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP with Workload Identity Federation
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: Configure NPM to use Artifact Registry
        run: |
          cat << EOF > .npmrc
            @expense-manager:registry=https://europe-west1-npm.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/expense-manager-repo/
            //europe-west1-npm.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/expense-manager-repo/:_authToken="${{ steps.auth.outputs.access_token }}"
            //europe-west1-npm.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/expense-manager-repo/:always-auth=true
          EOF

      - name: Install dependencies
        run: npm install

      - name: Publish to Artifact Registry
        run: npm publish
