name: Continuous Integration

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'client/**'
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - name: format check
        run: npm run format:check
      - name: lint check
        run: npm run lint:check
      - name: type check
        run: npm run type:check